name: CI/CD for React Spring Boot Monorepo

on:
  push:
    branches: [ main ]
    paths: # Trigger only if changes in these paths
      - 'apps/frontend/**'
      - 'apps/backend/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/frontend/**'
      - 'apps/backend/**'
      - '.github/workflows/main.yml'

jobs:
  # Backend Jobs
  build-test-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    # Run only if changes in backend directory or workflow file
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && (
        startsWith(github.head_commit.message, '[backend]') ||
        contains(join(github.event.commits.*.modified, ' '), 'apps/backend/') ||
        contains(join(github.event.commits.*.added, ' '), 'apps/backend/') ||
        contains(join(github.event.commits.*.removed, ' '), 'apps/backend/') ||
        contains(join(github.event.commits.*.modified, ' '), '.github/workflows/main.yml')
      ))
    defaults:
      run:
        working-directory: ./apps/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: # ensure working-directory applies to actions/checkout too if needed, or use full paths
          fetch-depth: 0 # For analyzing changed files if needed by other tools

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle' # or 'gradle'

      - name: Build and test Backend
        run: ./gradlew bootJar -x test --info # Skipping tests here for brevity, enable them

      - name: Upload backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: apps/backend/build/libs/*.jar

  dockerize-push-backend:
    name: Dockerize and Push Backend
    needs: build-test-backend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Only on push to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download backend JAR
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: apps/backend/build/libs # Dockerfile expects JAR here relative to its build context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend # Build context is the backend app directory
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app-backend:latest

  # Frontend Jobs
  build-test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && (
        startsWith(github.head_commit.message, '[frontend]') ||
        contains(join(github.event.commits.*.modified, ' '), 'apps/frontend/') ||
        contains(join(github.event.commits.*.added, ' '), 'apps/frontend/') ||
        contains(join(github.event.commits.*.removed, ' '), 'apps/frontend/') ||
        contains(join(github.event.commits.*.modified, ' '), '.github/workflows/main.yml')
      ))
    defaults:
      run:
        working-directory: ./apps/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json # or yarn.lock

      - name: Install Frontend Dependencies
        run: npm ci # or yarn install --frozen-lockfile

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false # or yarn test --watchAll=false

      - name: Build Frontend App
        run: npm run build # or yarn build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: apps/frontend/dist

  dockerize-push-frontend:
    name: Dockerize and Push Frontend (React static assets)
    needs: build-test-frontend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: apps/frontend/build # Dockerfile expects build folder here

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend Docker image (React assets only)
        uses: docker/build-push-action@v5
        with:
          context: ./apps/frontend # Build context for frontend
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-app-frontend-assets:latest # Image contains only static assets

  # Deployment Job (runs after both backend and frontend images are pushed)
  deploy-to-vps:
    name: Deploy to VPS
    needs: [dockerize-push-backend, dockerize-push-frontend] # Depends on both image pushes
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (to get docker-compose.yml for VPS)
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22 # Default SSH port
          script: |
            # Create deployment directory if it doesn't exist
            mkdir -p ${{ secrets.VPS_DEPLOY_PATH }}
            cd ${{ secrets.VPS_DEPLOY_PATH }}

            # Copy the docker-compose.yml from the repo to the VPS
            # (Alternatively, have this file already on the VPS and just update images)
            # For this example, we'll assume you might update it via git.
            # Or, use scp action to copy it directly:
            # scp .github/deployment/docker-compose.vps.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_DEPLOY_PATH }}/docker-compose.yml

            echo "Pulling latest images..."
            docker compose -f ${{ secrets.VPS_DEPLOY_PATH }}/docker-compose.yml pull

            echo "Restarting services..."
            docker compose -f ${{ secrets.VPS_DEPLOY_PATH }}/docker-compose.yml up -d --remove-orphans

            echo "Cleaning up old images..."
            docker image prune -af
